<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Force HTTPS
    |--------------------------------------------------------------------------
    |
    | When enabled, all URLs generated by the application will use HTTPS
    | protocol. This is recommended for production environments.
    |
    */

    'force_https' => env('FORCE_HTTPS', true),

    /*
    |--------------------------------------------------------------------------
    | Secure Cookies
    |--------------------------------------------------------------------------
    |
    | When enabled, cookies will only be transmitted over HTTPS connections.
    | This is automatically applied when force_https is enabled in production.
    |
    */

    'secure_cookies' => env('SECURE_COOKIES', true),

    /*
    |--------------------------------------------------------------------------
    | HTTP Only Cookies
    |--------------------------------------------------------------------------
    |
    | When enabled, cookies will not be accessible via JavaScript, providing
    | protection against XSS attacks.
    |
    */

    'http_only_cookies' => env('HTTP_ONLY_COOKIES', true),

    /*
    |--------------------------------------------------------------------------
    | Same Site Cookie Policy
    |--------------------------------------------------------------------------
    |
    | Supported: "lax", "strict", "none", null
    |
    */

    'same_site' => env('COOKIE_SAME_SITE', 'lax'),

];
